--== CORE CONFIGS ==--
require('core/general')
require('core/bindings')

--== PLUGIN CONFIGS ==--
require('plugins/startify')
require('plugins/bufferline')
require('plugins/telescope')
-- require('plugins/mason')
require('plugins/autopairs')
require('plugins/toggleterm')
-- require('plugins/numbertoggle')
-- require('plugins/minimap')
require('plugins/scrollbar')
require('plugins/trouble')
require('plugins/todo-comments')
require('plugins/surround')
require('plugins/nvim-notify')
require('plugins/material')
require('plugins/lualine')
require('plugins/neotree')
require('plugins/noice')
